### ISSUE TITLE
Instantiate solver object from parameter object

### ISSUE THREAD

**Issue by lsoucasse** [ExPlanetology/aragog#13]
It would be useful to instantiate the solver object directly from a parameter object without going through parsing a config file. In Proteus, we will likely write a function that fills the aragog parameter class from Proteus options, and then send the parameter class to the solver.

**Comment by djbower** [comment]
The library I am using does support this feature:

https://github.com/ajatkj/typed_configparser

See usage examples in the documentation.  It's basically built on top of config parser so offers similar functionality (but is fully typed, which I personally like to use).  You are welcome to adjust the parsing as you wish and submit a PR.

**Comment by lsoucasse** [comment]
Thanks! I will investigate, maybe we don't need any change.

**Comment by lsoucasse** [comment]
I have looked into the typed config, but I don't see how I can write variables into the config string. Also it requires to discriminate between actual files (Path object `parser.read`) and typed config (string `parser.read_string`).

I have implemented instead a new default constructor for the solver class, see associated PR.
