### ISSUE TITLE
Python version 3.13

### ISSUE THREAD

**Issue by nichollsh** [ExPlanetology/aragog#18]
The current `pyproject.toml` restricts Python versions to 3.10 <= v < 3.13, which is annoying if you have version 3.13 installed.

The model seems to run just as fine with 3.13 as with 3.12, so we should update the `pyproject.toml` file correspondingly.

**Comment by djbower** [comment]
Agreed.  Done in [54b969c](https://github.com/ExPlanetology/aragog/commit/54b969cad99e0794a85f1c1ba5645e7df5c13774)
