### ISSUE TITLE
Write output profiles to files

### ISSUE THREAD

**Issue by nichollsh** [ExPlanetology/aragog#19]
It is my understanding that aragog cannot yet save 1D quantities (e.g. temperature vs pressure, viscosity vs pressure) to the disk. This would be useful for debugging at the moment, and analysis later on.

SPIDER used JSON files but maybe we could consider something with better performance like HD5, NetCDF, or Zarr. Personally I am a fan of NetCDF.

I have locally made a branch for doing this, and it seems to work well so far. See the branch here: https://github.com/ExPlanetology/aragog/tree/hn/writefiles

**Comment by djbower** [comment]
Yes, I'm happy with whatever approach you prefer for writing to the disk.  Feel free to issue a PR when you have something working.

**Comment by nichollsh** [comment]
Thanks!
