### ISSUE TITLE
Pypi release is dated

### ISSUE THREAD

**Issue by stefsmeets** [ExPlanetology/aragog#24]
The current version of aragog on pypi dates from april this year. Are there any plans to make a new release?

**Comment by djbower** [comment]
I'm happy for anyone in the PROTEUS team to make aragog releases as and when they wish, since this will probably help to keep packages in sync with the overall PROTEUS development.  Both Laurent and Harrison are "maintainers" of the aragog repo so I think they can make releases.

**Comment by djbower** [comment]
Maybe it would also help if I add @lsoucasse and @nichollsh as maintainers of the package on PyPI?  I forget exactly how I set everything up now, but maybe some automation would be nice.  E.g.:

https://medium.com/@blackary/publishing-a-python-package-from-github-to-pypi-in-2024-a6fb8635d45d

**Comment by nichollsh** [comment]
If you could add us as maintainers on PyPI that would be great, thanks @djbower!

**Comment by djbower** [comment]
Send me your PyPI user names and I'll add you

**Comment by lsoucasse** [comment]
My PyPI user name is lsoucass. Thanks for adding is Dan.

**Comment by nichollsh** [comment]
Mine is nichollsh

**Comment by djbower** [comment]
Both added!

**Comment by nichollsh** [comment]
Seems like this doesn't give us permissions to setup the release from GitHub. Maybe only the owner can do it? Or maybe there's another permission that needs to be changed somewhere.

**Comment by nichollsh** [comment]
Actually, this might be wrong. I think we just need to register the GitHub as a publisher for the package and setup a workflow. We can copy the workflow used for the FormingWorlds packages.

**Comment by djbower** [comment]
I just made @nichollsh admin for the aragog repo, which is technically the same level of permissions that I have as the owner.   Feel free to setup the repo as you wish.

**Comment by lsoucasse** [comment]
Just created a branch to set up a release workflow.

**Comment by nichollsh** [comment]
Thanks @lsoucasse. I have tried to set this up on PyPI but I think only people with the role of "owner" can do it - it says I don't have the required permissions.

@djbower I think if you follow this link it should set it up?
https://pypi.org/manage/project/aragog/settings/publishing/?project_name=aragog&owner=ExPlanetology&repository=aragog&workflow_filename=publish.yaml&provider=github

**Comment by djbower** [comment]
Thanks - I just followed the link and it seemed to work

**Comment by nichollsh** [comment]
I created a release on GitHub (now deleted) but it didn't actually work. The current workflow `publish.yaml` is broken because there's no actual build step. We need to rework this with `poetry build`.

**Comment by nichollsh** [comment]
(And then we should make a release to PyPI, since we still haven't updated it)

**Comment by lsoucasse** [comment]
Thanks @nichollsh for fixing this, I thought the pip install command would do it.
