### ISSUE TITLE
Evaluating solid-liquid according the melting curves

### ISSUE THREAD

**Issue by planetmariana** [ExPlanetology/aragog#26]
@djbower  @timlichtenberg @lsoucasse 

I tested the lookup tables for the three different test cases in Aragog. For just the solid and liquid phase it works, but when running the mixed phase test fails due to divergences between the solidus and liquidus. In this specific case, there was a warning showing that there were negative values encountered on the computation of the inviscid velocity, so when computing the square root of that number was finding an imaginary number (this is from phase.py):

```   # Inviscid velocity
        self._inviscid_velocity = ( velocity_prefactor * self._evaluator.mesh.basic.mixing_length_squared) / 16
        self._inviscid_velocity[~self.is_convective] = 0  # Must be super-adiabatic
        self._inviscid_velocity[self._is_convective] = np.sqrt(self._inviscid_velocity[self._is_convective] )
```

 Then, I tracked these properties to see where was the error coming from, and I found that the problem was coming from the property  **velocity_prefactor**, which is declared like this (also in phase.py):

```
       velocity_prefactor: np.ndarray = (self.phase_basic.gravitational_acceleration()
            * self.phase_basic.thermal_expansivity()
            * -self._super_adiabatic_temperature_gradient)
```

So, the term that was raising negative numbers came from the **thermal_expansivity**  that follows Solomatov+2007:
```   
    self._thermal_expansivity = self.delta_density() / self.delta_fusion() / self.density()
```
     
 In that case, when tracking these properties I realised that the problem was coming from de computation of **delta_density**. In this case, is following the P-T conditions and not the melting curves:

```
def set_pressure(self, pressure: np.ndarray) -> None:
        super().set_pressure(pressure)
        self._solid.set_temperature(self.solidus())
        self._solid.set_pressure(pressure)
        self._liquid.set_temperature(self.solidus())
        self._liquid.set_pressure(pressure)
        self._delta_density = self._solid.density() - self._liquid.density()
        self._delta_fusion = self.liquidus() - self.solidus()
        self._heat_capacity = self.settings.latent_heat_of_fusion / self.delta_fusion()
```

In this way, this properties must be reviewed to check if they follow the EoS of solidus and liquidus in order to avoid divergence in the mixed phase.

**Comment by djbower** [comment]
Fixed in #26.
