### ISSUE TITLE
Converting data tables from entropy to pressure

### ISSUE THREAD

**Issue by djbower** [ExPlanetology/aragog#6]
In `scripts/` there is a `convert_datatables.py` prototype that eventually should convert the original C Spider lookup tables by entropy to lookup by temperature.  The script currently maps entropy to temperature and plots the data (note that the plot is misleading because it suggests a regular grid, but in fact it interpolates outside the actual data bounds which are revealed by the contours). Depending how the lookup is implemented, it may be necessary to interpolate the mapped pressure-temperature lookup data to a regular grid to allow fast and consistent indexing.  Prototype output in `data/1TPa-dk09-elec-free/temperature` shows that temperature is not regularly spaced.

It would probably be most sensible to somehow mask the data so that regions outside data have NaNs, whilst still allowing a regular grid format. Hence this script requires a few modifications to output the T-P data.  Also note that the prototype temperature output is not currently generated by the script, but rather older code that is below the new class structure.

**Comment by timlichtenberg** [comment]
Also relevant: https://github.com/ExPlanetology/aragog/issues/7

**Comment by planetmariana** [comment]
@lsoucasse @timlichtenberg @djbower 

The translation from entropy to temperature into a regular grid was done. The points where the interpolation is out of the bounds were filled with NaNs. You can check the comparison plots and the .dat files [here](https://drive.google.com/drive/folders/10OZw5LDMPEgnBFJI8NKNsW_tqJgYe4Vl?usp=share_link). The only thing is I couldn't resolve the small features near the surface when projecting the interpolation into the regular grid.
The functions that receives any pressure array and returns the solidus temperature according different parametrizations and the fit the original P-T anhydrous solidus from Aragog are given in the file solidus_functions.py

**Comment by planetmariana** [comment]
@lsoucasse @djbower @timlichtenberg 

Using the branch "add-output" with the last changes I was able to plot the different quantities with constant properties, but when introducing the lookup tables with regular grids and NaNs as showed above, at least one by one for testing purposes. It complains for arrays with NaNs or infs, I was debugging to find where was punctually the problem. Turns out, when computing dTdt, is calling the quantity capacitance that is computed through the -staggered density- and somehow it's computing these properties at the nodes with out-of bounds values where the NaNs are. That's my idea about the problem. Do you have any insight on how to avoid this? 
![lookup_tables_debugging](https://github.com/user-attachments/assets/db59ecb6-1e9a-4b14-9537-96706775b15a)

**Comment by djbower** [comment]
Depending on how the boundary conditions are implemented, it may be that the code is trying to calculate values at the innermost and outermost boundaries of the mesh.  Due to numerical noise or zero values, the values at these points might not be evaluated correctly.  Notably, P is zero or maybe even slightly negative at the uppermost boundary, so perhaps this is propagating an error into the calculation (NaN).  It's often convenient to evaluate all properties at all grid points and then apply boundary conditions afterwards, but maybe it will be necessary to only evaluate properties at the innermost nodes of the basic mesh (excluding the top and bottom boundaries).  More debugging might be required to identify exactly which boundary is throwing the NaN.

**Comment by djbower** [comment]
@planetmariana  Test the latest main and let me know if everything seems in order.  Then we can look to remove the old entropy-pressure data tables which are no longer required.

**Comment by planetmariana** [comment]
@djbower I tested the latest main  but when running mixed phase it complains on output.py when declaring:

```
    def pressure_GPa_basic(self) -> npt.NDArray:
        return self.evaluator.mesh.basic.eos.pressure * self.parameters.scalings.pressure * 1.0e-9
```

AttributeError: 'FixedMesh' object has no attribute 'eos'

**Comment by djbower** [comment]
Fixed in 8650910 (I believe)

**Comment by djbower** [comment]
@planetmariana  Can you compare with output from my 2018 paper, the Solomatov paper that gives the equations for the mixed phase properties, and the C-spider code?  See if you can spot a sign error somewhere or whether something is missing an absolute evaluation abs().  The individual phases look well behaved, so hopefully it's something trivial that is amiss.

**Comment by planetmariana** [comment]
@timlichtenberg @djbower @lsoucasse 

I finally managed to read correctly the lookup tables, matching the indexes of P,T on the function LookupProperty2D, now the interpolation made by RectBivariateSpline is doing exactly the same as griddata see the comparison below. I created a new branch 2Dproperties where I did the corresponding changes in phase.py, punctually here: https://github.com/ExPlanetology/aragog/blob/4ca277817209d3b7a04f2d29e5ef2275d1e23843/aragog/phase.py#L124 Also I change output.py to plot the melt fraction correctly in the case of solid and liquid phases only (phi=0 and phi=1) , and 

 I uploaded the most recent version of the lookup tables to the OSF repository up to 135GPa with the solidus and liquidus of Monteux+2016. You can check now how the different phases looks like. I will add these new changes to PROTEUS to start testing. Let me know what you think !

![difference](https://github.com/user-attachments/assets/9376d74b-4eb1-474c-a2bb-46903b83c40f)
**Liquid phase**
![liquid](https://github.com/user-attachments/assets/1fffbb80-4943-4255-8f11-33d334a8bbb5)
**Solid phase**
![solid](https://github.com/user-attachments/assets/4bb6c83f-4ba7-4e9c-aeb1-1c113ede439a)
**Mixed phase**
![mixed_phase](https://github.com/user-attachments/assets/a313c285-e430-4f10-82b7-74bb8fd0ecfb)

**Comment by timlichtenberg** [comment]
Hi Mariana, well done finding and correcting this issue! As we discussed in the meeting I am not quite certain about the behaviour of the mixed phase, but let's first now fix the numerical issue that you have outlined above, and then in a second step evaluate the physical behaviour of the mixed phase. I think we can discuss this further in the upcoming PR then. :-)

**Comment by djbower** [comment]
Good work.  Yes feel free to wrap up these improvements into a PR and I'll review and merge.
