### ISSUE TITLE
Core cooling model

### ISSUE THREAD

**Issue by timlichtenberg** [ExPlanetology/aragog#8]
At the moment, the inner boundary conditions only allow fixed temperature conditions. The 0-D core cooling model from SPIDER should be recoded.

**Comment by timlichtenberg** [comment]
Naive question on this. In the spirit of PROTEUS modularity, couldn't we fuse 2*Aragog to each other, one for the core, one for the mantle? We'd need core material properties etc, but could this work in principle?

**Comment by djbower** [comment]
Yes it would be possible in the long run.  To do this wisely would require having an "interior dynamic domain" class, from which you can then assemble (stack) several on top of each other.  Then you could also do things like have a magma ocean either side of a solid domain, if desired.  This approach would also enable SPIDER to approximate the hemispheric energy flow from a hot day side to a cooler night side.  I believe that Shami used this approach with his 1-D code to approximate the behavior of a 2-D system.

**Comment by lsoucasse** [comment]
Is this prescribing the bottom heat flux such that:
- $q = \rho c_p dT^{core}/dt R^{core}$
Or something like:
- $q = h (T^{bottom} - T^{core})

**Comment by djbower** [comment]
Here are some old notes on this, which certainly need checking and maybe re-deriving.  But you should be able to reverse-engineer the boundary condition quite quickly with these pointers, as well as comparing to the implementation in cSpider

[160711_core_cooling_model.pdf](https://github.com/user-attachments/files/17374615/160711_core_cooling_model.pdf)

**Comment by lsoucasse** [comment]
Thanks for sharing your notes,
I understand now it is assumed that the decrease rate of the core temperature $\frac{dT^{core}}{dt}$ is proportional to the decrease rate of the boundary temperature $\frac{dT^{CMB}}{dt}$.
Now I need to figure out how to translate it into the finite volume formulation.

**Comment by djbower** [comment]
You can compare with cSPIDER for pointers.  The implementation should be near identical.

**Comment by lsoucasse** [comment]
![Screenshot 2024-11-05 at 13 50 26](https://github.com/user-attachments/assets/44f0f479-d638-4bdd-b5f2-d77061ca5a3a)

**Comment by lsoucasse** [comment]
This is actually well explained in your 2018 paper Dan, see Eq. 37 copied above which relates the inner boundary heat flux ($\mathcal{F}_p$) with the heat flux on top of the lowest cell ($\mathcal{F}_{p-1}$)
